### PR TITLE
language

### PR DESCRIPTION
**Pull request by lethihaiyenb**
[Redmine](https://edu-redmine.sun-asterisk.vn/issues/28505)
What : cài đặt song ngữ

### CODE REVIEW

**Review by ReRolPxE — APPROVED** [review]

**Review by tonytit — APPROVED** [review]

**Comment by lethihaiyenb** [comment]
ready

**Comment by lethihaiyenb** [comment]
ready

**Comment by lethihaiyenb** [comment]
ready

**Comment by lethihaiyenb** [comment]
ready

**Review by thaodtd-0665 — APPROVED** [review]

**Pull request merged**
